version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:2024.w44
        privileged: true
        container_name : oai-gNB1
        environment:
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        ports:
            - "2021:2021"
        networks:
            public_net:
                ipv4_address : 192.168.70.160
        volumes:
            - ./conf/gnb.sa.bandn78.fr1.106PRB.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        entrypoint:
            - /bin/bash
            - -c
            - |
                /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf --sa -E --rfsim --log_config.global_log_options level,nocolor,time &
                tail -f /dev/null
networks:
    public_net:
        external:
            name : phine-net
